import { motion, useInView, AnimatePresence } from 'framer-motion'
import { useRef, useState } from 'react'
import { useAuth } from './contexts/AuthContext'
import { supabase } from './lib/supabase'

declare global {
  interface Window {
    Razorpay: any;
  }
}

export function Pricing() {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })
  const { profile } = useAuth()
  const [showSuccessModal, setShowSuccessModal] = useState(false)

  const handlePayment = async () => {
    if (!profile) {
      alert("Please sign in to upgrade to Premium.");
      return;
    }
    
    // In a real application, you should create the order on your backend first.
    // This is a placeholder order_id for demonstration purposes.
    const options = {
      key: import.meta.env.VITE_RAZORPAY_KEY_ID, // Use environment variable
      amount: "1", // Amount in subunits (e.g., 1 cent = $0.01)
      currency: "USD",
      name: "Workflow Memory",
      description: "Premium Tier Access",
      // order_id: "order_9A33XWu170gUtm", // Use order ID generated by your backend
      handler: async function (_response: any) {
        // Update user status in Supabase
        const { error } = await supabase
          .from('profiles')
          .update({ subscription_tier: 'premium' })
          .eq('id', profile.id);
          
        if (error) {
          console.error("Error updating premium status:", error);
          alert("Payment successful, but failed to update status. Please contact support.");
        } else {
          setShowSuccessModal(true);
        }
      },
      prefill: {
        name: "John Doe",
        email: "john@example.com",
        contact: "+919876543210"
      },
      theme: {
        color: "#5A7CFF"
      }
    };
    
    if (window.Razorpay) {
      const rzp = new window.Razorpay(options);
      rzp.on('payment.failed', function (response: any) {
        alert("Payment Failed: " + response.error.description);
      });
      rzp.open();
    } else {
      alert("Razorpay SDK not loaded");
    }
  };

  return (
    <section id="pricing" ref={ref} style={{ padding: '120px 24px', position: 'relative' }}>
      {/* Top divider line */}
      <div style={{
        position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)',
        width: 400, height: 1,
        background: 'linear-gradient(90deg, transparent, rgba(90,124,255,0.2), transparent)',
      }} />

      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.7 }}
        style={{ textAlign: 'center', marginBottom: 48 }}
      >
        <div style={{
          display: 'inline-block', padding: '6px 16px', borderRadius: 100,
          background: 'rgba(90, 124, 255, 0.08)', border: '1px solid rgba(90, 124, 255, 0.2)',
          fontSize: 12, color: 'var(--primary-light)', letterSpacing: '0.08em', textTransform: 'uppercase',
          fontWeight: 700, marginBottom: 24,
        }}>Pricing</div>

        <h2 className="section-title" style={{ marginBottom: 16 }}>
          Freemium or Premium, your choice
        </h2>
        <p style={{ color: 'var(--text-muted)', maxWidth: 780, margin: '0 auto', fontSize: 16, lineHeight: 1.7, fontWeight: 400 }}>
          Workflow Memory is available now as a freemium product: core features are free to use forever.
          Upgrade to our thoughtfully priced Premium tier to unlock power user features and cloud sync capabilities.
        </p>
      </motion.div>

      <div style={{ maxWidth: 1000, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
        {/* Free tier card */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="brutalist-card">
          <div className="brutalist-card-bg"></div>
          <div className="brutalist-card-front">
            <div>
              <div style={{ fontSize: 14, fontWeight: 800, color: '#000000', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 12 }}>Freemium</div>
              <div style={{ fontSize: 36, fontWeight: 800, color: '#000000', marginBottom: 16, fontFamily: 'Outfit, sans-serif' }}>
                Free <span style={{ fontSize: 16, fontWeight: 700, color: '#555555' }}>/ forever</span>
              </div>
              <p style={{ color: '#333333', marginBottom: 24, lineHeight: 1.7, fontSize: '0.95rem', fontWeight: 600 }}>
                Full access to essential features — capture, organize, and revisit your browsing sessions without limits.
              </p>
            </div>
            <div style={{ borderTop: '2px solid #000000', paddingTop: 20, display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#000000' }}>
                <span style={{ color: '#000000' }}>✓</span> Offline-first local storage
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#000000' }}>
                <span style={{ color: '#000000' }}>✓</span> Max 3 workflows
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#000000', opacity: 0.6 }}>
                <span style={{ color: '#000000' }}>✗</span> No tracking of copied text, prompts, or forms
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#000000', opacity: 0.6 }}>
                <span style={{ color: '#000000' }}>✗</span> No searching through workflows
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#000000', opacity: 0.6 }}>
                <span style={{ color: '#000000' }}>✗</span> No advanced search tags
              </div>
            </div>
            <button 
              onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              className="btn-brutalist-outline dark-variant"
              style={{ marginTop: 24 }}
            >
              Add Extension
            </button>
          </div>
        </motion.div>

        {/* Premium tier card */}
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="brutalist-card premium">
          <div className="brutalist-card-bg"></div>
          <div className="brutalist-card-front">
            <div>
              <div style={{ fontSize: 14, fontWeight: 800, color: '#ffffff', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 12 }}>Premium</div>
              <div style={{ fontSize: 36, fontWeight: 800, color: '#ffffff', marginBottom: 16, fontFamily: 'Outfit, sans-serif' }}>
                $0.01 <span style={{ fontSize: 16, fontWeight: 700, color: '#e0e7ff' }}>/ forever</span>
              </div>
              <p style={{ color: '#f8fafc', marginBottom: 24, lineHeight: 1.7, fontSize: '0.95rem', fontWeight: 600 }}>
                Unlock the full potential of your research with unlimited workflows, advanced workflow searching, and powerful filtering capabilities.
              </p>
            </div>
            <div style={{ borderTop: '2px solid #ffffff', paddingTop: 20, display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#ffffff' }}>
                <span style={{ color: '#ffffff' }}>✓</span> Unlimited workflows
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#ffffff' }}>
                <span style={{ color: '#ffffff' }}>✓</span> Tracking for copied text, prompts & forms
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#ffffff' }}>
                <span style={{ color: '#ffffff' }}>✓</span> Search through workflows
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#ffffff' }}>
                <span style={{ color: '#ffffff' }}>✓</span> Advanced filters (Time, Tags: Prompts, Pages, Sites, Copied text)
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 700, color: '#ffffff' }}>
                <span style={{ color: '#ffffff' }}>✓</span> All future updates
              </div>
            </div>
            {profile?.subscription_tier === 'premium' ? (
              <div style={{
                marginTop: 24, padding: '12px 24px',
                background: '#5A7CFF', color: '#ffffff',
                textAlign: 'center', fontWeight: 800, fontSize: 14,
                border: '3px solid #ffffff',
                boxShadow: '4px 4px 0px 0px #ffffff'
              }}>
                You are already Premium!
              </div>
            ) : (
              <button 
                onClick={handlePayment}
                className="btn-brutalist-heavy"
                style={{ marginTop: 24 }}
              >
                Upgrade to Premium
              </button>
            )}
          </div>
        </motion.div>
      </div>

      {/* Success Modal */}
      <AnimatePresence>
        {showSuccessModal && (
          <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999
          }}>
            <motion.div 
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              style={{
                background: 'var(--bg-card)', padding: 40, borderRadius: 16,
                maxWidth: 400, width: '90%', textAlign: 'center',
                border: '1px solid rgba(90, 124, 255, 0.2)',
                boxShadow: '0 20px 40px rgba(0,0,0,0.4)'
              }}
            >
              <div style={{ fontSize: 48, marginBottom: 16 }}>🎉</div>
              <h3 style={{ fontSize: 24, fontWeight: 800, color: '#fff', marginBottom: 12 }}>Welcome to Premium!</h3>
              <p style={{ color: 'var(--text-muted)', marginBottom: 24, fontSize: 15, lineHeight: 1.6 }}>
                Your account has been upgraded. You now have access to exclusive features:
              </p>
              <div style={{ textAlign: 'left', background: 'rgba(90,124,255,0.05)', padding: 16, borderRadius: 8, marginBottom: 24 }}>
                <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
                  <span style={{ color: 'var(--primary)' }}>⚡</span>
                  <span style={{ color: '#fff', fontSize: 14 }}>Unlimited cloud backups</span>
                </div>
                <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
                  <span style={{ color: 'var(--primary)' }}>🔍</span>
                  <span style={{ color: '#fff', fontSize: 14 }}>Advanced OCR searching</span>
                </div>
                <div style={{ display: 'flex', gap: 12 }}>
                  <span style={{ color: 'var(--primary)' }}>🤖</span>
                  <span style={{ color: '#fff', fontSize: 14 }}>Priority AI processing</span>
                </div>
              </div>
              <button
                onClick={() => setShowSuccessModal(false)}
                style={{
                  padding: '10px 24px', borderRadius: 8, background: 'var(--primary)',
                  color: '#fff', border: 'none', fontWeight: 600, cursor: 'pointer',
                  width: '100%', fontSize: 14
                }}
              >
                Start using Premium
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </section>
  )
}
